name: Modicator CI
on: [push]
jobs:
  docs:
    if: github.ref == 'refs/heads/main'
    name: Pandoc to Vimdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: modicator
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto generate vimdoc"
          branch: ${{ github.head_ref }}
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Neovim
        shell: bash
        run: |
          mkdir -p /tmp/nvim
          wget -q https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -O /tmp/nvim/nvim.appimage
          cd /tmp/nvim
          chmod a+x ./nvim.appimage
          ./nvim.appimage --appimage-extract
          echo "/tmp/nvim/squashfs-root/usr/bin/" >> $GITHUB_PATH
      - name: Run Tests
        run: |
          nvim --version
          [ ! -d tests ] && exit 0
          make test
